
version: '2'
services:

    shadowsocks:
        build: "./shadowsocks"
        ports:
            - "8388:8388/tcp"
            - "8388:8388/udp"
        environment:
            SERVER_ADDR: "0.0.0.0"
            SERVER_PORT: "8388"
            PASSWORD: "password"
            METHOD: "aes-256-cfb"
            TIMEOUT: 300
            WORKERS: 10
        restart: "always"

    shadowsocksr:
        build: "./shadowsocksr"
        ports:
            - "8488:8488/tcp"
            - "8488:8488/udp"
        environment:
            SERVER_ADDR: "0.0.0.0"
            SERVER_PORT: "8488"
            PASSWORD: "password"
            METHOD: "aes-256-cfb"
            OBFS: "http_simple"
            TIMEOUT: 300
            WORKERS: 10
            PROTOCOL: "auth_sha1_v4"
        restart: "always"

    dnscrypt:
        image: "mengbo/docker-dnscrypt-wrapper"
        volumes:
            - "./app_dnscrypt/data/:/usr/local/share/dnscrypt-wrapper/"
        environment:
            RESOLVER_ADDRESS: "8.8.8.8"
            RESOLVER_PORT: "53"
            LISTEN_PORT: "5353"
            PROVIDER_NAME: "2.dnscrypt-cert.example.com"
        network_mode: "host"
        restart: "always"

    ipsec:
        build: "./ipsec"
        environment:
            USERNAME: "vpn"
            PASSWORD: "password"
            DNS_ADDR_1: "8.8.8.8"
            DNS_ADDR_2: "8.8.4.4"
        privileged: true
        network_mode: "host"
        restart: "always"

